### ISSUE TITLE
Error on aws lambda

### ISSUE THREAD

**Issue by robertellam** [Satish-A-Wadekar/ffmpeg-with-AWS-Lambda#1]
Hi, my function works fine on my local machine but when I deploy to AWS Lambda I get the error:

`TypeError: Cannot create property 'stack' on string 'Could not find ffmpeg executable, tried "/var/task/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/var/task/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"'`

Do you have any idea how I fix this?

**Comment by Satish-A-Wadekar** [comment]
Hi Robert Ellam
   first of all extremely sorry for this much late reply, my apology. 

Now let's resolve this issue, i just wanted to know on which platform you have built the code package ? 

if you refer to my article [https://medium.com/@satish.a.wadekar/ffmpeg-with-aws-lambda-under-node-js-platform-5cbc0ad13f57](link) i have mentioned that we need to build the package from Linux OS, bcoz at the time of build, it loads all the dependencies in our deployable package, which we upload on S3. please let me know if you have any further queries.

**Comment by robertellam** [comment]
Hi Satish,

That was the problem, I was building on macOS.

I forced the linux dependencies by doing:
`npm install @ffmpeg-installer/linux-x64 -force --no-save`

Thanks,
Robert.

**Comment by Satish-A-Wadekar** [comment]
great, good to hear that your issue got resolved... 👍 
happy Coding
